### ISSUE TITLE
越测越慢，直到全部失败，重启软件后才恢复正常

### ISSUE THREAD

**Issue by dream2333** [Apipost-Team/runnerGo#16]

**Comment by wjzhangq** [comment]
压测是外置服务。这个是go语音内部分配调度的一个bug，暂时没有好的解决方案。
我们后续版本增加一个可以自由开关压测服务，以及重启压测服务的功能，无需在重启整个软件。

**Comment by dream2333** [comment]
> 压测是外置服务。这个是go语音内部分配调度的一个bug，暂时没有好的解决方案。 我们后续版本增加一个可以自由开关压测服务，以及重启压测服务的功能，无需在重启整个软件。

具体的原因是什么呢？我这边用go-wrk就是正常的
