### ISSUE TITLE
https接口自签名证书发送失败问题

### ISSUE THREAD

**Issue by zhangboqi** [Apipost-Team/runnerGo#9]
当压测的接口为自签名的证书时，golang的http库默认是要验证服务器证书链和地址的，这时doWork发送请求时就会失败，所有的请求都是error的
需要在worker.go的第59行修改tls.Config添加InsecureSkipVerify:true
如下代码：

```
tr := &http.Transport{
MaxConnsPerHost:    0,
IdleConnTimeout:    20 * time.Second,
DisableKeepAlives:  false,
DisableCompression: false,
TLSClientConfig: &tls.Config{
	CipherSuites:       append(defaultCipherSuites[8:], defaultCipherSuites[:8]...),
	InsecureSkipVerify: true,
}, //绕过特征检测
TLSHandshakeTimeout: 10 * time.Second,
}
```
其实个人认为既然是用于测试的工具，是否应该默认就可以添加这个配置呢，或者提供配置的地方以允许忽略证书验证

**Comment by zhangboqi** [comment]
希望能提供更好的方案

**Comment by zhangboqi** [comment]
我再这个pr中添加了InsecureSkipVerify配置，希望能提供更好的解决方式 #10

**Comment by wjzhangq** [comment]
> 当压测的接口为自签名的证书时，golang的http库默认是要验证服务器证书链和地址的，这时doWork发送请求时就会失败，所有的请求都是error的 需要在worker.go的第59行修改tls.Config添加InsecureSkipVerify:true 如下代码：
> 
> ```
> tr := &http.Transport{
> MaxConnsPerHost:    0,
> IdleConnTimeout:    20 * time.Second,
> DisableKeepAlives:  false,
> DisableCompression: false,
> TLSClientConfig: &tls.Config{
> 	CipherSuites:       append(defaultCipherSuites[8:], defaultCipherSuites[:8]...),
> 	InsecureSkipVerify: true,
> }, //绕过特征检测
> TLSHandshakeTimeout: 10 * time.Second,
> }
> ```
> 
> 其实个人认为既然是用于测试的工具，是否应该默认就可以添加这个配置呢，或者提供配置的地方以允许忽略证书验证

非常感谢建议。
